package ni.gob.minsa.hsf.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblcatgen generated by hbm2java
 */
@Entity
@Table(name = "tblcatgen", catalog = "salud_familiar")
public class Tblcatgen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTiposvar;
	private int idTipocat;
	private String nombre;

	public Tblcatgen() {
	}

	public Tblcatgen(int idTiposvar, int idTipocat, String nombre) {
		this.idTiposvar = idTiposvar;
		this.idTipocat = idTipocat;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "id_tiposvar", nullable = false)
	public int getIdTiposvar() {
		return this.idTiposvar;
	}

	public void setIdTiposvar(int idTiposvar) {
		this.idTiposvar = idTiposvar;
	}

	@Column(name = "id_tipocat", nullable = false)
	public int getIdTipocat() {
		return this.idTipocat;
	}

	public void setIdTipocat(int idTipocat) {
		this.idTipocat = idTipocat;
	}

	@Column(name = "nombre", nullable = false, length=55)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
