package ni.gob.minsa.hsf.domain.estructura;

// Generated Mar 28, 2014 11:26:42 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CategoriasUnidades generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIAS_UNIDADES", catalog = "HSF", uniqueConstraints = {
		@UniqueConstraint(columnNames = "NOMBRE"),
		@UniqueConstraint(columnNames = "CODIGO") })
public class CategoriasUnidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1988602285535459381L;
	private long categoriaUnidadId;
	private String nombre;
	private String urlImagen;
	private long codigo;
	private char pasivo;

	public CategoriasUnidades() {
	}

	public CategoriasUnidades(long categoriaUnidadId, String nombre,
			long codigo, char pasivo) {
		this.categoriaUnidadId = categoriaUnidadId;
		this.nombre = nombre;
		this.codigo = codigo;
		this.pasivo = pasivo;
	}

	public CategoriasUnidades(long categoriaUnidadId, String nombre,
			String urlImagen, long codigo, char pasivo) {
		this.categoriaUnidadId = categoriaUnidadId;
		this.nombre = nombre;
		this.urlImagen = urlImagen;
		this.codigo = codigo;
		this.pasivo = pasivo;
	}

	@Id
	@Column(name = "CATEGORIA_UNIDAD_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCategoriaUnidadId() {
		return this.categoriaUnidadId;
	}

	public void setCategoriaUnidadId(long categoriaUnidadId) {
		this.categoriaUnidadId = categoriaUnidadId;
	}

	@Column(name = "NOMBRE", unique = true, nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "URL_IMAGEN", length = 2000)
	public String getUrlImagen() {
		return this.urlImagen;
	}

	public void setUrlImagen(String urlImagen) {
		this.urlImagen = urlImagen;
	}

	@Column(name = "CODIGO", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	@Column(name = "PASIVO", nullable = false, length = 1)
	public char getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(char pasivo) {
		this.pasivo = pasivo;
	}

}
