package ni.gob.minsa.hsf.domain.estructura;

// Generated Mar 28, 2014 11:26:42 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TiposUnidades generated by hbm2java
 */
@Entity
@Table(name = "TIPOS_UNIDADES", catalog = "HSF", uniqueConstraints = {
		@UniqueConstraint(columnNames = "CODIGO"),
		@UniqueConstraint(columnNames = "NOMBRE") })
public class TiposUnidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7696717696782898758L;
	private long tipoUnidadId;
	private String nombre;
	private Byte orden;
	private byte codigo;
	private char pasivo;
	private Serializable fechaRegistro;
	private String usuarioRegistro;
	private String marcador;

	public TiposUnidades() {
	}

	public TiposUnidades(long tipoUnidadId, String nombre, byte codigo,
			char pasivo, Serializable fechaRegistro, String usuarioRegistro) {
		this.tipoUnidadId = tipoUnidadId;
		this.nombre = nombre;
		this.codigo = codigo;
		this.pasivo = pasivo;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	public TiposUnidades(long tipoUnidadId, String nombre, Byte orden,
			byte codigo, char pasivo, Serializable fechaRegistro,
			String usuarioRegistro, String marcador) {
		this.tipoUnidadId = tipoUnidadId;
		this.nombre = nombre;
		this.orden = orden;
		this.codigo = codigo;
		this.pasivo = pasivo;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
		this.marcador = marcador;
	}

	@Id
	@Column(name = "TIPO_UNIDAD_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getTipoUnidadId() {
		return this.tipoUnidadId;
	}

	public void setTipoUnidadId(long tipoUnidadId) {
		this.tipoUnidadId = tipoUnidadId;
	}

	@Column(name = "NOMBRE", unique = true, nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ORDEN", precision = 2, scale = 0)
	public Byte getOrden() {
		return this.orden;
	}

	public void setOrden(Byte orden) {
		this.orden = orden;
	}

	@Column(name = "CODIGO", unique = true, nullable = false, precision = 2, scale = 0)
	public byte getCodigo() {
		return this.codigo;
	}

	public void setCodigo(byte codigo) {
		this.codigo = codigo;
	}

	@Column(name = "PASIVO", nullable = false, length = 1)
	public char getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(char pasivo) {
		this.pasivo = pasivo;
	}

	@Column(name = "FECHA_REGISTRO", nullable = false)
	public Serializable getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Serializable fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 100)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Column(name = "MARCADOR", length = 80)
	public String getMarcador() {
		return this.marcador;
	}

	public void setMarcador(String marcador) {
		this.marcador = marcador;
	}

}
