package ni.gob.minsa.hsf.domain.poblacion;

// Generated Mar 28, 2014 11:26:42 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Comunidades generated by hbm2java
 */
@Entity
@Table(name = "COMUNIDADES", catalog = "HSF", uniqueConstraints = @UniqueConstraint(columnNames = "CODIGO"))
public class Comunidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1758825531378545362L;
	private long comunidadId;
	private String nombre;
	private String sector;
	private String referencias;
	private Character tipoArea;
	private String codigo;
	private String caracteristicas;
	private char pasivo;
	private Serializable fechaRegistro;
	private String usuarioRegistro;
	private BigDecimal longitud;
	private BigDecimal latitud;
	private String zona;

	public Comunidades() {
	}

	public Comunidades(long comunidadId, String nombre, String sector,
			String codigo, char pasivo, Serializable fechaRegistro,
			String usuarioRegistro) {
		this.comunidadId = comunidadId;
		this.nombre = nombre;
		this.sector = sector;
		this.codigo = codigo;
		this.pasivo = pasivo;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	public Comunidades(long comunidadId, String nombre, String sector,
			String referencias, Character tipoArea, String codigo,
			String caracteristicas, char pasivo, Serializable fechaRegistro,
			String usuarioRegistro, BigDecimal longitud, BigDecimal latitud,
			String zona) {
		this.comunidadId = comunidadId;
		this.nombre = nombre;
		this.sector = sector;
		this.referencias = referencias;
		this.tipoArea = tipoArea;
		this.codigo = codigo;
		this.caracteristicas = caracteristicas;
		this.pasivo = pasivo;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
		this.longitud = longitud;
		this.latitud = latitud;
		this.zona = zona;
	}

	@Id
	@Column(name = "COMUNIDAD_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getComunidadId() {
		return this.comunidadId;
	}

	public void setComunidadId(long comunidadId) {
		this.comunidadId = comunidadId;
	}

	@Column(name = "NOMBRE", nullable = false, length = 400)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "SECTOR", nullable = false, length = 28)
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	@Column(name = "REFERENCIAS", length = 4000)
	public String getReferencias() {
		return this.referencias;
	}

	public void setReferencias(String referencias) {
		this.referencias = referencias;
	}

	@Column(name = "TIPO_AREA", length = 1)
	public Character getTipoArea() {
		return this.tipoArea;
	}

	public void setTipoArea(Character tipoArea) {
		this.tipoArea = tipoArea;
	}

	@Column(name = "CODIGO", unique = true, nullable = false, length = 36)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "CARACTERISTICAS", length = 4000)
	public String getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(String caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	@Column(name = "PASIVO", nullable = false, length = 1)
	public char getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(char pasivo) {
		this.pasivo = pasivo;
	}

	@Column(name = "FECHA_REGISTRO", nullable = false)
	public Serializable getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Serializable fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 100)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Column(name = "LONGITUD", precision = 10, scale = 6)
	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	@Column(name = "LATITUD", precision = 10, scale = 6)
	public BigDecimal getLatitud() {
		return this.latitud;
	}

	public void setLatitud(BigDecimal latitud) {
		this.latitud = latitud;
	}

	@Column(name = "ZONA", length = 200)
	public String getZona() {
		return this.zona;
	}

	public void setZona(String zona) {
		this.zona = zona;
	}

}
