package ni.gob.minsa.hsf.domain.poblacion;

// Generated Mar 28, 2014 11:26:42 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Divisionpolitica generated by hbm2java
 */
@Entity
@Table(name = "DIVISIONPOLITICA", catalog = "HSF", uniqueConstraints = @UniqueConstraint(columnNames = "CODIGO_NACIONAL"))
public class Divisionpolitica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4744800056954925186L;
	private long divisionpoliticaId;
	private Divisionpolitica divisionpolitica;
	private String nombre;
	private Long administracion;
	private BigDecimal latitud;
	private BigDecimal longitud;
	private String codigoIso;
	private String codigoNacional;
	private char pasivo;
	private Serializable fechaRegistro;
	private String usuarioRegistro;
	private Short codigoCse;
	private Long dependenciaSilais;

	public Divisionpolitica() {
	}

	public Divisionpolitica(long divisionpoliticaId, String nombre,
			String codigoNacional, char pasivo, Serializable fechaRegistro,
			String usuarioRegistro) {
		this.divisionpoliticaId = divisionpoliticaId;
		this.nombre = nombre;
		this.codigoNacional = codigoNacional;
		this.pasivo = pasivo;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	public Divisionpolitica(long divisionpoliticaId,
			Divisionpolitica divisionpolitica, String nombre,
			Long administracion, BigDecimal latitud, BigDecimal longitud,
			String codigoIso, String codigoNacional, char pasivo,
			Serializable fechaRegistro, String usuarioRegistro,
			Short codigoCse, Long dependenciaSilais) {
		this.divisionpoliticaId = divisionpoliticaId;
		this.divisionpolitica = divisionpolitica;
		this.nombre = nombre;
		this.administracion = administracion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.codigoIso = codigoIso;
		this.codigoNacional = codigoNacional;
		this.pasivo = pasivo;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
		this.codigoCse = codigoCse;
		this.dependenciaSilais = dependenciaSilais;
	}

	@Id
	@Column(name = "DIVISIONPOLITICA_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getDivisionpoliticaId() {
		return this.divisionpoliticaId;
	}

	public void setDivisionpoliticaId(long divisionpoliticaId) {
		this.divisionpoliticaId = divisionpoliticaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPENDENCIA")
	public Divisionpolitica getDivisionpolitica() {
		return this.divisionpolitica;
	}

	public void setDivisionpolitica(Divisionpolitica divisionpolitica) {
		this.divisionpolitica = divisionpolitica;
	}

	@Column(name = "NOMBRE", nullable = false, length = 400)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ADMINISTRACION", precision = 10, scale = 0)
	public Long getAdministracion() {
		return this.administracion;
	}

	public void setAdministracion(Long administracion) {
		this.administracion = administracion;
	}

	@Column(name = "LATITUD", precision = 10, scale = 6)
	public BigDecimal getLatitud() {
		return this.latitud;
	}

	public void setLatitud(BigDecimal latitud) {
		this.latitud = latitud;
	}

	@Column(name = "LONGITUD", precision = 10, scale = 6)
	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	@Column(name = "CODIGO_ISO", length = 2)
	public String getCodigoIso() {
		return this.codigoIso;
	}

	public void setCodigoIso(String codigoIso) {
		this.codigoIso = codigoIso;
	}

	@Column(name = "CODIGO_NACIONAL", unique = true, nullable = false, length = 4)
	public String getCodigoNacional() {
		return this.codigoNacional;
	}

	public void setCodigoNacional(String codigoNacional) {
		this.codigoNacional = codigoNacional;
	}

	@Column(name = "PASIVO", nullable = false, length = 1)
	public char getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(char pasivo) {
		this.pasivo = pasivo;
	}

	@Column(name = "FECHA_REGISTRO", nullable = false)
	public Serializable getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Serializable fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 100)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Column(name = "CODIGO_CSE", precision = 3, scale = 0)
	public Short getCodigoCse() {
		return this.codigoCse;
	}

	public void setCodigoCse(Short codigoCse) {
		this.codigoCse = codigoCse;
	}

	@Column(name = "DEPENDENCIA_SILAIS", precision = 10, scale = 0)
	public Long getDependenciaSilais() {
		return this.dependenciaSilais;
	}

	public void setDependenciaSilais(Long dependenciaSilais) {
		this.dependenciaSilais = dependenciaSilais;
	}

}
