package ni.gob.minsa.comunitaria.hsf.domain;


/**
 * Tblcatgen generated by hbm2java
 */

public class CatGen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTiposvar;
	private int idTipocat;
	private String nombre;

	public CatGen() {
	}

	public CatGen(int idTiposvar, int idTipocat, String nombre) {
		this.idTiposvar = idTiposvar;
		this.idTipocat = idTipocat;
		this.nombre = nombre;
	}

	public int getIdTiposvar() {
		return this.idTiposvar;
	}

	public void setIdTiposvar(int idTiposvar) {
		this.idTiposvar = idTiposvar;
	}

	public int getIdTipocat() {
		return this.idTipocat;
	}

	public void setIdTipocat(int idTipocat) {
		this.idTipocat = idTipocat;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
