package ni.gob.minsa.hsf.domain;

// Generated 12-06-2012 03:38:40 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;

import org.joda.time.DateTime;


/**
 * Divisionpolitica generated by hbm2java
 */

public class Divisionpolitica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8435843122476741682L;
	private long divisionpoliticaId;
	private String nombre;
	private Long dependencia;
	private Long administracion;
	private BigDecimal latitud;
	private BigDecimal longitud;
	private String codigoIso;
	private String codigoNacional;
	private char pasivo;
	private DateTime fechaRegistro;
	private String usuarioRegistro;
	private Short codigoCse;

	public Divisionpolitica() {
	}

	public Divisionpolitica(long divisionpoliticaId, String nombre,
			String codigoNacional, char pasivo, DateTime fechaRegistro,
			String usuarioRegistro) {
		this.divisionpoliticaId = divisionpoliticaId;
		this.nombre = nombre;
		this.codigoNacional = codigoNacional;
		this.pasivo = pasivo;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	public Divisionpolitica(long divisionpoliticaId, String nombre,
			Long dependencia, Long administracion, BigDecimal latitud,
			BigDecimal longitud, String codigoIso, String codigoNacional,
			char pasivo, DateTime fechaRegistro, String usuarioRegistro,
			Short codigoCse) {
		this.divisionpoliticaId = divisionpoliticaId;
		this.nombre = nombre;
		this.dependencia = dependencia;
		this.administracion = administracion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.codigoIso = codigoIso;
		this.codigoNacional = codigoNacional;
		this.pasivo = pasivo;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
		this.codigoCse = codigoCse;
	}

	
	public long getDivisionpoliticaId() {
		return this.divisionpoliticaId;
	}

	public void setDivisionpoliticaId(long divisionpoliticaId) {
		this.divisionpoliticaId = divisionpoliticaId;
	}

	
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	
	public Long getDependencia() {
		return this.dependencia;
	}

	public void setDependencia(Long dependencia) {
		this.dependencia = dependencia;
	}

	
	public Long getAdministracion() {
		return this.administracion;
	}

	public void setAdministracion(Long administracion) {
		this.administracion = administracion;
	}

	
	public BigDecimal getLatitud() {
		return this.latitud;
	}

	public void setLatitud(BigDecimal latitud) {
		this.latitud = latitud;
	}

	
	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	
	public String getCodigoIso() {
		return this.codigoIso;
	}

	public void setCodigoIso(String codigoIso) {
		this.codigoIso = codigoIso;
	}

	
	public String getCodigoNacional() {
		return this.codigoNacional;
	}

	public void setCodigoNacional(String codigoNacional) {
		this.codigoNacional = codigoNacional;
	}

	
	public char getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(char pasivo) {
		this.pasivo = pasivo;
	}

	
	public DateTime getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(DateTime fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}
	
	
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	
	public Short getCodigoCse() {
		return this.codigoCse;
	}

	public void setCodigoCse(Short codigoCse) {
		this.codigoCse = codigoCse;
	}
	
	@Override
	public String toString(){
		return this.getNombre();
	}

}
