package ni.gob.minsa.hsf.domain.estructura;

// Generated Mar 28, 2014 11:26:42 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Catalogos generated by hbm2java
 */
@Entity
@Table(name = "CATALOGOS", catalog = "HSF", uniqueConstraints = {
		@UniqueConstraint(columnNames = "CODIGO"),
		@UniqueConstraint(columnNames = { "VALOR", "DEPENDENCIA" }) })
public class Catalogos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4856427150098576781L;
	private long catalogoId;
	private String valor;
	private String codigo;
	private boolean pasivo;
	private short orden;
	private String descripcion;
	private String dependencia;
	private String usuarioRegistro;
	private Serializable fechaRegistro;
	private boolean final_;

	public Catalogos() {
	}

	public Catalogos(long catalogoId, String valor, String codigo,
			boolean pasivo, short orden, String usuarioRegistro,
			Serializable fechaRegistro, boolean final_) {
		this.catalogoId = catalogoId;
		this.valor = valor;
		this.codigo = codigo;
		this.pasivo = pasivo;
		this.orden = orden;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
		this.final_ = final_;
	}

	public Catalogos(long catalogoId, String valor, String codigo,
			boolean pasivo, short orden, String descripcion,
			String dependencia, String usuarioRegistro,
			Serializable fechaRegistro, boolean final_) {
		this.catalogoId = catalogoId;
		this.valor = valor;
		this.codigo = codigo;
		this.pasivo = pasivo;
		this.orden = orden;
		this.descripcion = descripcion;
		this.dependencia = dependencia;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
		this.final_ = final_;
	}

	@Id
	@Column(name = "CATALOGO_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCatalogoId() {
		return this.catalogoId;
	}

	public void setCatalogoId(long catalogoId) {
		this.catalogoId = catalogoId;
	}

	@Column(name = "VALOR", nullable = false, length = 400)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "CODIGO", unique = true, nullable = false, length = 200)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "PASIVO", nullable = false, precision = 1, scale = 0)
	public boolean isPasivo() {
		return this.pasivo;
	}

	public void setPasivo(boolean pasivo) {
		this.pasivo = pasivo;
	}

	@Column(name = "ORDEN", nullable = false, precision = 3, scale = 0)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	@Column(name = "DESCRIPCION", length = 800)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "DEPENDENCIA", length = 200)
	public String getDependencia() {
		return this.dependencia;
	}

	public void setDependencia(String dependencia) {
		this.dependencia = dependencia;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 400)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Column(name = "FECHA_REGISTRO", nullable = false)
	public Serializable getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Serializable fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "FINAL", nullable = false, precision = 1, scale = 0)
	public boolean isFinal_() {
		return this.final_;
	}

	public void setFinal_(boolean final_) {
		this.final_ = final_;
	}

}
